# Generated by Django 3.2.4 on 2021-10-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0017_auto_20201124_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
