# Generated by Django 4.0.1 on 2022-02-09 10:06

# Generated by Django 4.0.1 on 2022-03-04 10:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0018_auto_20211010_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benef_name', models.CharField(max_length=30, unique=True)),
                ('benef_contact', models.EmailField(max_length=54, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='securities',
            name='beneficary',
        ),
        migrations.RemoveField(
            model_name='securities',
            name='sectype',
        ),
        migrations.AddField(
            model_name='securities',
            name='sec_type',
            field=models.CharField(choices=[('FD', 'Fd'), ('MIS', 'Mis'), ('SIP', 'Sip'), ('INSR', 'Insr')], default='FD', max_length=20, verbose_name='Security Type'),
        ),
        migrations.DeleteModel(
            name='Beneficary',
        ),
    ]
